name: Parsers test

on:
  push:
    paths:
      - 'src/main/kotlin/org/dokiteam/doki/parsers/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-trigger-jitpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build
        run: ./gradlew assemble

      - name: Trigger JitPack build for doki-exts
        run: |
          curl -X POST "https://jitpack.io/com/github/hoangxg4/doki-exts/main" \
            -u ${{ secrets.JITPACK_TOKEN }}:
