name: Parsers test

on:
    workflow_dispatch:
    push:
        paths:
            - 'src/main/kotlin/org/dokiteam/doki/parsers/**'

permissions:
    contents: read

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'temurin'
                    cache: 'gradle'
            -   run: ./gradlew assemble
